Repository SOPT-all/36-COLLABORATION-WEB-HYUNDAICARD, pull requests merged in 2025-05, with the labels that each got.

#2 [Init] 프로젝트 생성
  hyundai-card/.gitignore
  hyundai-card/README.md
  hyundai-card/biome.json
  hyundai-card/config/typescript/base.json
  hyundai-card/config/typescript/package.json
  hyundai-card/config/typescript/react-library.json
  hyundai-card/config/typescript/react.json
  hyundai-card/index.html
  hyundai-card/package.json
  hyundai-card/pnpm-lock.yaml
  hyundai-card/src/App.css
  hyundai-card/src/App.tsx
  hyundai-card/src/main.tsx
  hyundai-card/src/pages/.gitkeep
  hyundai-card/src/shared/apis/.gitkeep
  hyundai-card/src/shared/assets/.gitkeep
  hyundai-card/src/shared/components/.gitkeep
  hyundai-card/src/shared/constants/.gitkeep
  hyundai-card/src/shared/hooks/.gitkeep
  hyundai-card/src/shared/mocks/.gitkeep
  hyundai-card/src/shared/pages/.gitkeep
  hyundai-card/src/shared/router/.gitkeep
  hyundai-card/src/shared/styles/.gitkeep
  hyundai-card/src/shared/types/.gitkeep
  hyundai-card/src/shared/utils/.gitkeep
  hyundai-card/src/vite-env.d.ts
  hyundai-card/tsconfig.app.json
  hyundai-card/tsconfig.json
  hyundai-card/tsconfig.node.json
  hyundai-card/vite.config.ts
Labels: 지욱, init

#6 [Init] PR template 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 정민, init

#7 [Init] svgr, path alias 세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: 제성, init

#12 [Init] CODEOWNERS 파일 추가
  .github/CODEOWNERS
Labels: 지욱, init

#10 [Init] Tanstack-query 초기세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/shared/utils/query-client.ts
Labels: 인영 🐠, init

#31 [Feat] 폰트 수정
  src/styles/tokens/font-styles.css.ts
  src/styles/tokens/typography.css.ts
Labels: 정민 🐳, style, refactor

#34 [Feat] chip 컴포넌트 구현
  public/svg/icon_arrow_down.svg
  public/svg/icon_arrow_up.svg
  public/svg/icon_close.svg
  src/assets/svg/IconArrowDown.tsx
  src/assets/svg/IconArrowUp.tsx
  src/assets/svg/IconClose.tsx
  src/assets/svg/index.ts
  src/shared/components/chips/chip.css.ts
  src/shared/components/chips/chip.stories.tsx
  src/shared/components/chips/chip.tsx
  src/shared/utils/get-size-by-content.ts
  src/styles/font/font.css
  src/styles/theme-provider.tsx
Labels: 제성, feat

#19 [Feat] Card 공통 컴포넌트 제작
  src/shared/components/card/card.css.ts
  src/shared/components/card/card.tsx
Labels: 제성, feat

#21 [Feat] text-button 공통 컴포넌트 제작
  public/svg/right-arrow.svg
  src/assets/svg/RightArrow.tsx
  src/assets/svg/index.ts
  src/shared/components/text-button/text-button.css.ts
  src/shared/components/text-button/text-button.tsx
Labels: 제성, feat

#23 [Feat] 내게 맞는 카드 찾기 - 플로팅 카드 공통 컴포넌트 제작
  public/svg/svg_hyunddai_symbol.svg
  src/assets/svg/SvgHyunddaiSymbol.tsx
  src/assets/svg/index.ts
  src/shared/components/own-your-card/own-your-card.css.ts
  src/shared/components/own-your-card/own-your-card.tsx
Labels: 제성, feat

#39 [Feat] 현대카드 favicon 추가
  index.html
  public/hyundai_favicon.ico
Labels: 지욱, feat

#37 [Feat] 헤더 & 푸터 컴포넌트 퍼블리싱
  biome.json
  public/svg/footer_web_1.svg
  public/svg/footer_web_2.svg
  public/svg/icon_applepay.svg
  public/svg/icon_hamburge.svg
  public/svg/icon_search.svg
  public/svg/svg_hyundai_logo.svg
  public/svg/vector_stroke.svg
  src/assets/svg/FooterWeb1.tsx
  src/assets/svg/FooterWeb2.tsx
  src/assets/svg/IconApplepay.tsx
  src/assets/svg/IconHamburge.tsx
  src/assets/svg/IconSearch.tsx
  src/assets/svg/SvgHyundaiLogo.tsx
  src/assets/svg/VectorStroke.tsx
  src/assets/svg/index.ts
  src/pages/home/home.tsx
  src/pages/my/my.tsx
  src/shared/components/footer/contact-list.css.ts
  src/shared/components/footer/contact-list.tsx
  src/shared/components/footer/corporate-list.css.ts
  src/shared/components/footer/corporate-list.tsx
  src/shared/components/footer/footer.css.ts
  src/shared/components/footer/footer.tsx
  src/shared/components/footer/legal-list.css.ts
  src/shared/components/footer/legal-list.tsx
  src/shared/components/footer/link-list.css.ts
  src/shared/components/footer/link-list.tsx
  src/shared/components/header/header.css.ts
  src/shared/components/header/header.tsx
  src/shared/router/global-layout.css.ts
  src/shared/router/global-layout.tsx
  src/shared/router/lazy.ts
  src/shared/router/path.ts
  src/shared/router/router.tsx
  src/styles/global.css.ts
  src/styles/reset.css.ts
  src/styles/theme-provider.tsx
  src/styles/tokens/font-styles.css.ts
Labels: 지욱, feat

#33 [Feat] main event component 구현
  public/svg/img_event1.svg
  src/shared/components/main-event/main-event.css.ts
  src/shared/components/main-event/main-event.tsx
Labels: 정민 🐳, feat

#44 [Feat] axios 기본 설정
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/shared/apis/axios-instance.ts
  src/shared/apis/service.ts
  src/shared/components/header/header.tsx
  src/shared/types/api.ts
  src/styles/tokens/font-styles.css.ts
Labels: 제성, feat

#40 [Feat] progress bar 컴포넌트
  public/svg/ad_play.svg
  public/svg/ad_stop.svg
  src/assets/svg/AdPlay.tsx
  src/assets/svg/AdStop.tsx
  src/assets/svg/index.ts
  src/shared/components/progress-bar/progress-bar.css.ts
  src/shared/components/progress-bar/progress-bar.tsx
Labels: 정민 🐳, feat

#42 [Feat] 드롭다운 컴포넌트 구현
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  config/typescript/package.json
  src/assets/svg/IconArrowDown.tsx
  src/assets/svg/IconArrowUp.tsx
  src/shared/components/carousel/use-drag.ts
  src/shared/components/chips/chip.css.ts
  src/shared/components/chips/chip.tsx
  src/shared/components/dropdown/dropdown.css.ts
  src/shared/components/dropdown/dropdown.tsx
  src/shared/mocks/mock-dropdown-list.ts
  src/styles/theme.css.ts
  vite.config.ts
  vitest.workspace.ts
Labels: 인영 🐠, feat

#56 [Feat] 헤더 컴포넌트 동작 구현
  public/svg/Line_7.svg
  src/assets/svg/ImgEvent1.tsx
  src/assets/svg/Line7.tsx
  src/assets/svg/index.ts
  src/shared/apis/.gitkeep
  src/shared/components/header/header.css.ts
  src/shared/components/header/header.tsx
  src/shared/components/header/sub-content.css.ts
  src/shared/components/header/sub-content.tsx
  src/shared/components/login-button/login-button.css.ts
  src/shared/components/login-button/login-button.tsx
  src/styles/tokens/font-styles.css.ts
Labels: 지욱, feat

#50 [Feat] find card interaction+ 상단부
  public/svg/image_card_front.svg
  src/assets/svg/ImageCardFront.tsx
  src/assets/svg/index.ts
  src/pages/my/components/card-recommendation/card-info/card-info.css.ts
  src/pages/my/components/card-recommendation/card-info/card-info.tsx
  src/pages/my/components/card-recommendation/card-recommendation.css.ts
  src/pages/my/components/card-recommendation/card-recommendation.tsx
  src/pages/my/components/card-recommendation/header/header.css.ts
  src/pages/my/components/card-recommendation/header/header.tsx
  src/pages/my/components/card-recommendation/main-card/main-card.css.ts
  src/pages/my/components/card-recommendation/main-card/main-card.tsx
  src/pages/my/components/card-recommendation/mock.ts
Labels: 정민 🐳, feat

#54 [Fix] 드롭다운 배열 길이 따른 리스트 길이 css 오류 수정
  pnpm-lock.yaml
  src/shared/components/dropdown/dropdown.css.ts
  src/shared/components/dropdown/dropdown.tsx
  src/shared/mocks/mock-dropdown-list.ts
Labels: 인영 🐠, fix

#59 [Feat] posts api 연동 & 이벤트 카드 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/pages/home/components/post.css.ts
  src/pages/home/components/posts.tsx
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
  src/pages/home/hooks/get-posts.ts
  src/shared/apis/config.ts
  src/shared/components/header/header.css.ts
  src/shared/components/header/sub-content.css.ts
  src/shared/components/main-event/main-event.tsx
  src/styles/global.css.ts
Labels: 지욱, feat

#64 [Refactor] api 호출부 open-api 스펙 세팅
  package.json
  pnpm-lock.yaml
  src/pages/home/components/posts.tsx
  src/pages/home/home.tsx
  src/pages/home/hooks/get-posts.ts
  src/shared/apis/config.ts
  tsconfig.json
Labels: 지욱, feat, refactor

#52 [Feat] dropdown 기능제작 + home 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
  src/pages/home/one-your-card/dropdown-options.ts
  src/pages/home/one-your-card/header/header.css.ts
  src/pages/home/one-your-card/header/header.tsx
  src/pages/home/one-your-card/one-your-card-container.css.ts
  src/pages/home/one-your-card/one-your-card-container.tsx
  src/pages/home/one-your-card/selected-tag/selected-tag.css.ts
  src/pages/home/one-your-card/selected-tag/selected-tag.tsx
  src/shared/components/dropdown/dropdown.css.ts
  src/shared/components/dropdown/dropdown.tsx
  src/shared/router/global-layout.css.ts
Labels: 정민 🐳, feat

#61 [Feat] Subheader 구현
  src/pages/home/home.tsx
  src/pages/home/own-your-card/dropdown-options.ts
  src/pages/home/own-your-card/header/header.css.ts
  src/pages/home/own-your-card/header/header.tsx
  src/pages/home/own-your-card/own-your-card-container.css.ts
  src/pages/home/own-your-card/own-your-card-container.tsx
  src/pages/home/own-your-card/selected-tag/selected-tag.css.ts
  src/pages/home/own-your-card/selected-tag/selected-tag.tsx
  src/pages/my/components/card-recommendation/sub-header/sub-header.css.ts
  src/pages/my/components/card-recommendation/sub-header/sub-header.tsx
  src/pages/my/my.tsx
  src/shared/components/header/header.tsx
  src/shared/router/global-layout.tsx
Labels: 인영 🐠, feat

#65 [Feat] Accordion component
  pnpm-lock.yaml
  src/assets/svg/IconArrowUp.tsx
  src/pages/home/components/own-your-card-container.css.ts
  src/pages/home/components/own-your-card-container.tsx
  src/pages/home/components/own-your-header.css.ts
  src/pages/home/components/own-your-header.tsx
  src/pages/home/components/selected-tag.css.ts
  src/pages/home/components/selected-tag.tsx
  src/pages/home/constants/dropdown-options.ts
  src/pages/home/home.tsx
  src/pages/my/components/accordion/accordion.css.ts
  src/pages/my/components/accordion/accordion.tsx
  src/pages/my/hooks/get-tags.ts
  src/pages/my/hooks/tag-filter.ts
  src/pages/my/my.tsx
  src/shared/components/chips/chip.css.ts
  src/shared/components/chips/chip.tsx
  src/shared/hooks/use-accordion.ts
  src/shared/mocks/mock-tags.ts
  src/shared/utils/get-size-by-content.ts
Labels: 제성, feat

#70 [Feat] 캐러셀 홈화면에 퍼블리싱
  public/images/carousel/carousel-mock10.png
  public/images/carousel/carousel-mock11.png
  public/images/carousel/carousel-mock12.png
  public/images/carousel/carousel-mock13.png
  public/images/carousel/carousel-mock14.png
  public/images/carousel/carousel-mock15.png
  public/images/carousel/carousel-mock16.png
  public/images/carousel/carousel-mock17.png
  public/images/carousel/carousel-mock18.png
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
  src/shared/mocks/mockImgList.ts
Labels: 인영 🐠, feat

#67 [Feat] 홈페이지 사이드바 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/svg/icon_bulb.svg
  public/svg/icon_note.svg
  public/svg/icon_warning.svg
  src/assets/svg/IconBulb.tsx
  src/assets/svg/IconNote.tsx
  src/assets/svg/IconWarning.tsx
  src/assets/svg/index.ts
  src/pages/home/components/sidebar/sidebar.css.ts
  src/pages/home/components/sidebar/sidebar.tsx
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
  src/shared/components/login-button/login-button.css.ts
  src/shared/components/login-button/login-button.tsx
Labels: 인영 🐠, feat

#77 [Fix] 호버 이슈 수정
  src/shared/components/header/header.tsx
Labels: 정민 🐳, fix

#78 [Feat]다른 카드 추천 컴포넌트
  public/svg/image_visa.svg
  public/svg/mastercard.svg
  src/assets/svg/ImageVisa.tsx
  src/assets/svg/Mastercard.tsx
  src/assets/svg/index.ts
  src/pages/my/components/other-recommended-cards/other-recommended-cards.css.ts
  src/pages/my/components/other-recommended-cards/other-recommended-cards.tsx
Labels: 정민 🐳, feat

#71 [Feat] 내게 맞는 카드 찾기 사이드바 구현
  public/svg/icon_initialization.svg
  src/assets/svg/IconInitialization.tsx
  src/assets/svg/index.ts
  src/pages/my/components/range-slider/get-range-slider-idx.ts
  src/pages/my/components/range-slider/range-slider.tsx
  src/pages/my/components/range-slider/ranger-slier.css.ts
  src/pages/my/hooks/tag-filter.ts
  src/pages/my/my.tsx
  src/pages/own-your-card/own-your-card.css.ts
  src/pages/own-your-card/own-your-card.tsx
  src/pages/own-your-card/side-bar/side-bar.css.ts
  src/pages/own-your-card/side-bar/side-bar.tsx
  src/shared/components/filter-pane/filter-pane.tsx
  src/shared/components/header/header.tsx
Labels: 제성, feat

#74 [Feat] Chip(filter, selected mode) 호버시 플로팅 메세지 렌더링
  src/pages/my/components/accordion/accordion.css.ts
  src/pages/my/components/accordion/accordion.tsx
  src/shared/components/chips/chip-hover/chip-hover.css.ts
  src/shared/components/chips/chip-hover/chip-hover.tsx
Labels: 제성, feat

#82 [Feat] Suspense fall back UI 설정
  src/assets/lottie/loading.json
  src/shared/pages/.gitkeep
  src/shared/pages/loading.css.ts
  src/shared/pages/loading.tsx
  src/shared/router/router.tsx
Labels: 지욱, feat

#89 [feat] 내게 맞는 카드 찾기 페이지 api 연동
  README.md
  src/assets/svg/IconArrowDown.tsx
  src/pages/home/components/cards.tsx
  src/pages/my/components/accordion/accordion.tsx
  src/pages/my/components/card-recommendation/card-recommendation.tsx
  src/pages/my/components/card-recommendation/header/header.css.ts
  src/pages/my/components/card-recommendation/other-recommendation/other-recommendation.tsx
  src/pages/my/components/card-recommendation/other-recommendation/other-recommended-cards/other-recommended-cards.css.ts
  src/pages/my/components/card-recommendation/other-recommendation/other-recommended-cards/other-recommended-cards.tsx
  src/pages/my/components/card-recommendation/recommendation-description/recommendation-description.tsx
  src/pages/my/components/own-your-card-main.css.ts
  src/pages/my/components/own-your-card-main.tsx
  src/pages/my/hooks/tag-filter.ts
  src/pages/my/my.tsx
  src/pages/own-your-card/own-your-card.css.ts
  src/pages/own-your-card/own-your-card.tsx
  src/pages/own-your-card/side-bar/side-bar.css.ts
  src/shared/components/chips/chip.css.ts
  src/shared/components/chips/chip.tsx
Labels: 제성, feat
